name: Fetch and notify

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  fetch_and_notify:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
      - name: Run script
        run: ruby app.rb
        env:
          CONFIG: ${{ secrets.CONFIG }}
      - name: Save progress
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Save progress"
          commit_options: "--no-verify --signoff"
